ilogic/monitoring/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # cbg
    path('api/json/monitoring/dataklaim/CBG', views.api_json_data_klaim_CBG, name='api_json_data_klaim_CBG'),
    path('api/json/monitoring/dataklaim/verifikator/CBG', views.api_json_data_klaim_CBG_verifikator, name='api_json_data_klaim_CBG_verifikator'),
    path('api/json/monitoring/dataklaim/supervisor/CBG', views.api_json_data_klaim_CBG_supervisor, name='api_json_data_klaim_CBG_supervisor'),
    path('api/json/monitoring/dataklaim/CBG/stafak', views.api_json_data_klaim_CBG_stafak, name='api_json_data_klaim_CBG_stafak'),

    path('dataklaim/CBG', views.monitoring_data_klaim_CBG, name='monitoring_data_klaim_CBG'),
    path('dataklaim/CBG/verifikator', views.monitoring_data_klaim_CBG_verifikator, name='monitoring_data_klaim_CBG_verifikator'),
    path('dataklaim/CBG/supervisor', views.monitoring_data_klaim_CBG_supervisor, name='monitoring_data_klaim_CBG_supervisor'),
    path('dataklaim/CBG/stafak', views.monitoring_data_klaim_CBG_stafak, name='monitoring_data_klaim_CBG_stafak'),

    # obat
    path('api/json/monitoring/dataklaim/obat/verifikator', views.api_json_data_klaim_obat_verifikator, name='api_json_data_klaim_obat_verifikator'),
    path('api/json/monitoring/dataklaim/obat/stafak', views.api_json_data_klaim_obat_stafak, name='api_json_data_klaim_obat_stafak'),
    path('api/json/monitoring/dataklaim/obat/supervisor', views.api_json_data_klaim_obat_supervisor, name='api_json_data_klaim_obat_supervisor'),

    path('dataklaim/obat/verifikator/', views.monitoring_data_klaim_obat_verifikator,name='monitoring_data_klaim_obat_verifikator'),
    path('dataklaim/obat/stafak/', views.monitoring_data_klaim_obat_stafak, name='monitoring_data_klaim_obat_stafak'),
    path('dataklaim/obat/supervisor/', views.monitoring_data_klaim_obat_supervisor, name='monitoring_data_klaim_obat_supervisor'),

    # pending/dispute
    path('api/json/monitoring/dataklaim/cbg/pending/dispute', views.api_json_data_klaim_pending_dispute_CBG, name='api_json_data_klaim_pending_dispute_CBG'),
    path('api/json/monitoring/dataklaim/cbg/pending/dispute/stafak', views.api_json_data_klaim_pending_dispute_CBG_stafak, name='api_json_data_klaim_pending_dispute_CBG_stafak'),
    path('api/json/monitoring/dataklaim/cbg/pending/dispute/supervisor', views.api_json_data_klaim_pending_dispute_CBG_supervisor, name='api_json_data_klaim_pending_dispute_CBG_supervisor'),
    path('api/json/monitoring/dataklaim/obat/pending/dispute/verifikator', views.api_json_data_klaim_pending_dispute_obat_verifikator, name='api_json_data_klaim_pending_dispute_obat_verifikator'),
    path('api/json/monitoring/dataklaim/obat/pending/dispute/stafak', views.api_json_data_klaim_pending_dispute_obat_stafak, name='api_json_data_klaim_pending_dispute_obat_stafak'),
    path('api/json/monitoring/dataklaim/obat/pending/dispute/supervisor', views.api_json_data_klaim_pending_dispute_obat_supervisor, name='api_json_data_klaim_pending_dispute_obat_supervisor'),

    path('dataklaim/CBG/pending/dispute', views.monitoring_data_klaim_pending_dispute_CBG, name='monitoring_data_klaim_pending_dispute_CBG'),
    path('dataklaim/CBG/pending/dispute/stafak', views.monitoring_data_klaim_pending_dispute_CBG_stafak, name='monitoring_data_klaim_pending_dispute_CBG_stafak'),
    path('dataklaim/CBG/pending/dispute/supervisor', views.monitoring_data_klaim_pending_dispute_CBG_supervisor, name='monitoring_data_klaim_pending_dispute_CBG_supervisor'),
    path('dataklaim/obat/pending/dispute/verifikator', views.monitoring_data_klaim_pending_dispute_obat_verifikator, name='monitoring_data_klaim_pending_dispute_obat_verifikator'),
    path('dataklaim/obat/pending/dispute/stafak', views.monitoring_data_klaim_pending_dispute_obat_stafak, name='monitoring_data_klaim_pending_dispute_obat_stafak'),
    path('dataklaim/obat/pending/dispute/supervisor', views.monitoring_data_klaim_pending_dispute_obat_supervisor, name='monitoring_data_klaim_pending_dispute_obat_supervisor'),

    # hitung
    path('api/json/monitoring/dataklaim/hitung/verifikator', views.api_json_data_klaim_hitung_verifikator, name='api_json_data_klaim_hitung_verifikator'),
    path('api/json/monitoring/dataklaim/hitung/supervisor', views.api_json_data_klaim_hitung_supervisor, name='api_json_data_klaim_hitung_supervisor'),

    path('dataklaim/hitung/verifikator', views.monitoring_data_klaim_hitung_verifikator, name='monitoring_data_klaim_hitung_verifikator'),
    path('dataklaim/hitung/supervisor', views.monitoring_data_klaim_hitung_supervisor, name='monitoring_data_klaim_hitung_supervisor'),

]

ilogic/user/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('ubahpassword', views.ubahpassword, name='ubahpassword'),
    path('logout', views.user_logout, name='logout'),

    path('new-user/', views.create_user_kantor_cabang, name='web_usr_add'),
    path('kanca/', include([
        path('user/change/group/<pk>/', views.change_group, name='kanca_grp_change'),
        path('user/group/add/kantorcabang', views.add_group, name='kanca_grp_add'),
        path('user/change/password/<pk>/', views.change_password, name='kanca_usr_passwd'),
        path('', views.user_per_kanca, name='kanca_user_list')
    ])),

    path('faskes/', include([
        path('', views.user_per_faskes, name='cbg_user_list')
    ])),

    path('new-user/faskes/', views.create_user_faskes, name='create_user_faskes'),

    path('list/verifikator/', views.user_per_verifikator, name='user_per_verifikator'),
    path('edit/active/verifikator/<int:pk>/', views.edit_user_verifikator_active, name='edit_user_verifikator_active'),
    path('edit/staff/verifikator/<int:pk>/', views.edit_user_verifikator_staff, name='edit_user_verifikator_staff'),
]

ilogic/viis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from user import views
from user.views import dashboard

admin.site.site_header = "BPJS Kesehatan"
admin.site.site_title = "BPJS Kesehatan"
admin.site.index_title = "Selamat Datang di Portal BPJS Kesehatan"

admin.site.login = views.user_login

urlpatterns = [
    path('admin/ilogic/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('faskes/', include(('faskes.urls', 'faskes'), namespace='faskes')),
    path('klaim/', include(('klaim.urls', 'klaim'), namespace='klaim')),
    path('verifikator/', include(('verifikator.urls', 'verifikator'), namespace='verifikator')),
    path('staff/', include(('staff.urls', 'staff'), namespace='staff')),
    path('captcha/', include('captcha.urls')),
    path('monitoring/', include(('monitoring.urls', 'monitoring'), namespace='monitoring')),
    path('supervisor/', include(('supervisor.urls', 'supervisor'), namespace='supervisor')),
    # path('dokumentasi/', include(('dokumentasi.urls', 'dokumentasi'), namespace='dokumentasi')),
    path('supervisorkp/', include(('supervisorkp.urls', 'supervisorkp'), namespace='supervisorkp')),
    path('vpkaak/', include(('vpkaak.urls', 'vpkaak'), namespace='vpkaak')),
    path('metafisik/', include(('metafisik.urls', 'metafisik'), namespace='metafisik')),


    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ilogic/monitoring/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from klaim.models import DataKlaimCBG, DataKlaimObat
from user.decorators import permissions, check_device
from django.http import JsonResponse

from verifikator.models import HitungDataKlaim


@login_required
@check_device
@permissions(role=['verifikator'])
def api_json_data_klaim_CBG(request):
    # Get all KantorCabang associated with the user
    kantor_cabang_list = request.user.kantorcabang_set.all()

    # Build the queryset
    queryset = DataKlaimCBG.objects.select_related(
        'register_klaim', 'faskes', 'verifikator'
    ).filter(
        register_klaim__faskes__kantor_cabang__in=kantor_cabang_list,
        prosesklaim=False
    ).values(
        'register_klaim__nomor_register_klaim',
        'bupel',
        'faskes__nama',
        'verifikator__username',
        'status',
        'JNSPEL',
        'tgl_SLA'
    )

    data = list(queryset)
    return JsonResponse(data, safe=False)



@login_required
@check_device
@permissions(role=['verifikator'])
def monitoring_data_klaim_CBG(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_CBG.html', context=context)


@login_required
@check_device
@permissions(role=['verifikator'])
def api_json_data_klaim_CBG_verifikator(request):
    # Get all KantorCabang associated with the user
    kantor_cabang_list = request.user.kantorcabang_set.all()

    # Build the queryset
    queryset = DataKlaimCBG.objects.select_related(
        'register_klaim', 'faskes', 'verifikator'
    ).filter(
        register_klaim__faskes__kantor_cabang__in=kantor_cabang_list,
        prosesklaim=False,
        verifikator=request.user
    ).values(
        'register_klaim__nomor_register_klaim',
        'bupel',
        'faskes__nama',
        'verifikator__username',
        'status',
        'JNSPEL',
        'tgl_SLA'
    )

    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['verifikator'])
def monitoring_data_klaim_CBG_verifikator(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_CBG_verifikator.html', context=context)\



@login_required
@check_device
@permissions(role=['supervisor'])
def api_json_data_klaim_CBG_supervisor(request):
    # Get all KantorCabang associated with the user
    kantor_cabang_list = request.user.kantorcabang_set.all()

    # Build the queryset
    queryset = DataKlaimCBG.objects.select_related(
        'register_klaim', 'faskes', 'verifikator'
    ).filter(
        register_klaim__faskes__kantor_cabang__in=kantor_cabang_list,
        prosesklaim=False
    ).values(
        'register_klaim__nomor_register_klaim',
        'bupel',
        'faskes__nama',
        'verifikator__username',
        'status',
        'JNSPEL',
        'tgl_SLA'
    )

    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['supervisor'])
def monitoring_data_klaim_CBG_supervisor(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_CBG_supervisor.html', context=context)


@login_required
@check_device
@permissions(role=['verifikator'])
def api_json_data_klaim_hitung_verifikator(request):
    queryset = HitungDataKlaim.objects.filter(nomor_register_klaim__startswith=request.user.kantorcabang_set.all().first().kode_cabang,
                                              verifikator=request.user).\
        values('tglhitung', 'periodehitung', 'jenis_klaim', 'verifikator__username')
    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['verifikator'])
def monitoring_data_klaim_hitung_verifikator(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_hitung_verifikator.html', context=context)


@login_required
@check_device
@permissions(role=['supervisor'])
def api_json_data_klaim_hitung_supervisor(request):
    queryset = HitungDataKlaim.objects.filter(nomor_register_klaim__startswith=request.user.kantorcabang_set.all().first().kode_cabang,).\
        values('tglhitung', 'periodehitung', 'jenis_klaim', 'verifikator__username')
    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['supervisor'])
def monitoring_data_klaim_hitung_supervisor(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_hitung_supervisor.html', context=context)


@login_required
@check_device
@permissions(role=['verifikator'])
def api_json_data_klaim_pending_dispute_CBG(request):
    status_klaim = ('Pending', 'Dispute', 'Pembahasan', 'Tidak Layak')
    # Get all KantorCabang associated with the user
    kantor_cabang_list = request.user.kantorcabang_set.all()

    # Build the queryset
    queryset = DataKlaimCBG.objects.select_related(
        'register_klaim', 'faskes', 'verifikator'
    ).filter(
        register_klaim__faskes__kantor_cabang__in=kantor_cabang_list,
        prosesklaim=True,
        status__in=status_klaim,
    ).values(
        'register_klaim__nomor_register_klaim',
        'bupel',
        'faskes__nama',
        'verifikator__username',
        'status',
        'JNSPEL',
        'tgl_SLA'
    )

    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['verifikator'])
def monitoring_data_klaim_pending_dispute_CBG(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_pending_dispute_CBG.html', context=context)


@login_required
@check_device
@permissions(role=['adminAK'])
def api_json_data_klaim_CBG_stafak(request):
    # Get all KantorCabang associated with the user
    kantor_cabang_list = request.user.kantorcabang_set.all()

    # Build the queryset
    queryset = DataKlaimCBG.objects.select_related(
        'register_klaim', 'faskes', 'verifikator'
    ).filter(
        register_klaim__faskes__kantor_cabang__in=kantor_cabang_list,
        prosesklaim=False,
    ).values(
        'register_klaim__nomor_register_klaim',
        'bupel',
        'faskes__nama',
        'verifikator__username',
        'status',
        'JNSPEL',
        'tgl_SLA'
    )
    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['adminAK'])
def monitoring_data_klaim_CBG_stafak(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_CBG_stafak.html', context=context)


@login_required
@check_device
@permissions(role=['adminAK'])
def api_json_data_klaim_pending_dispute_CBG_stafak(request):
    status_klaim = ('Pending', 'Dispute', 'Pembahasan', 'Tidak Layak')
    # Get all KantorCabang associated with the user
    kantor_cabang_list = request.user.kantorcabang_set.all()

    # Build the queryset
    queryset = DataKlaimCBG.objects.select_related(
        'register_klaim', 'faskes', 'verifikator'
    ).filter(
        register_klaim__faskes__kantor_cabang__in=kantor_cabang_list,
        prosesklaim=True,
        status__in=status_klaim,
    ).values(
        'register_klaim__nomor_register_klaim',
        'bupel',
        'faskes__nama',
        'verifikator__username',
        'status',
        'JNSPEL',
        'tgl_SLA'
    )
    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['adminAK'])
def monitoring_data_klaim_pending_dispute_CBG_stafak(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_pending_dispute_CBG_stafak.html', context=context)


@login_required
@check_device
@permissions(role=['supervisor'])
def api_json_data_klaim_pending_dispute_CBG_supervisor(request):
    status_klaim = ('Pending', 'Dispute', 'Pembahasan', 'Tidak Layak')
    # Get all KantorCabang associated with the user
    kantor_cabang_list = request.user.kantorcabang_set.all()

    # Build the queryset
    queryset = DataKlaimCBG.objects.select_related(
        'register_klaim', 'faskes', 'verifikator'
    ).filter(
        register_klaim__faskes__kantor_cabang__in=kantor_cabang_list,
        prosesklaim=True,
        status__in=status_klaim,
    ).values(
        'register_klaim__nomor_register_klaim',
        'bupel',
        'faskes__nama',
        'verifikator__username',
        'status',
        'JNSPEL',
        'tgl_SLA'
    )
    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['supervisor'])
def monitoring_data_klaim_pending_dispute_CBG_supervisor(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_pending_dispute_CBG_supervisor.html', context=context)


############################
# Obat #####################
############################


@login_required
@check_device
@permissions(role=['verifikator'])
def api_json_data_klaim_obat_verifikator(request):
    # Retrieve all KantorCabang associated with the user
    kantor_cabang_list = request.user.kantorcabang_set.all()

    # Build the queryset using related fields
    queryset = DataKlaimObat.objects.select_related('register_klaim', 'faskes', 'verifikator').filter(
        register_klaim__faskes__kantor_cabang__in=kantor_cabang_list,
        prosesklaim=False,
    ).values(
        'register_klaim__nomor_register_klaim',
        'bupel',
        'faskes__nama',
        'verifikator__username',
        'status',
        'KdJenis',
        'tgl_SLA'
    )

    data = list(queryset)
    return JsonResponse(data, safe=False)


@login_required
@check_device
@permissions(role=['verifikator'])
def monitoring_data_klaim_obat_verifikator(request):
    context = {}
    return render(request, 'monitoring/monitoring_data_klaim_obat_verifikator.html', context=context)


@login_required
@check_device
@permissions(role=['adminAK'])

ilogic/templates/monitoring/monitoring_data_klaim_CBG_stafak.html
{% extends 'base.html' %}

{% block content %}
<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card table-card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>Monitoring Data Klaim CBG</h5>
        </div>
    <div id="output" style="margin: 30px;"></div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.js" integrity="sha512-XgJh9jgd6gAHu9PcRBBAp0Hda8Tg87zi09Q2639t0tQpFFQhGpeCgaiEFji36Ozijjx9agZxB0w53edOFGCQ0g==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.css" integrity="sha512-BDStKWno6Ga+5cOFT9BUnl9erQFzfj+Qmr5MDnuGqTQ/QYDO1LPdonnF6V6lBO6JI13wg29/XmPsufxmCJ8TvQ==" crossorigin="anonymous" />

<script>
    // scroller active
    $('#dashboard_cbg').addClass('active');
    $('#vk').addClass('active');
    // pivot table js
    $(function(){
    $.getJSON("{% url 'monitoring:api_json_data_klaim_CBG_stafak' %}", function(mps) {
        $("#output").pivotUI(mps,
            { rows: ["tgl_SLA", "faskes__nama", "register_klaim__nomor_register_klaim", "JNSPEL", "bupel", ], cols: ["verifikator__username", "status"] },
            false
        );
    });
 });
</script>
{% endblock %}

ilogic/templates/monitoring/monitoring_data_klaim_CBG_supervisor.html
{% extends 'base.html' %}

{% block content %}
<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card table-card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>Monitoring Tugas Verifikator Klaim CBG</h5>
        </div>
    <div id="output" style="margin: 30px;"></div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.js" integrity="sha512-XgJh9jgd6gAHu9PcRBBAp0Hda8Tg87zi09Q2639t0tQpFFQhGpeCgaiEFji36Ozijjx9agZxB0w53edOFGCQ0g==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.css" integrity="sha512-BDStKWno6Ga+5cOFT9BUnl9erQFzfj+Qmr5MDnuGqTQ/QYDO1LPdonnF6V6lBO6JI13wg29/XmPsufxmCJ8TvQ==" crossorigin="anonymous" />

<script>
    // scroller active
    $('#dashboard_cbg').addClass('active');
    $('#vk').addClass('active');
    // pivot table js
    $(function(){
    $.getJSON("{% url 'monitoring:api_json_data_klaim_CBG_supervisor' %}", function(mps) {
        $("#output").pivotUI(mps,
            { rows: ["tgl_SLA", "faskes__nama", "register_klaim__nomor_register_klaim", "JNSPEL", "bupel", ], cols: ["verifikator__username", "status"] },
            false
        );
    });
 });
</script>
{% endblock %}

ilogic/templates/monitoring/monitoring_data_klaim_CBG_verifikator.html
{% extends 'base.html' %}

{% block content %}
<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card table-card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>Monitoring Tugas Verifikator Klaim CBG</h5>
        </div>
    <div id="output" style="margin: 30px;"></div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.js" integrity="sha512-XgJh9jgd6gAHu9PcRBBAp0Hda8Tg87zi09Q2639t0tQpFFQhGpeCgaiEFji36Ozijjx9agZxB0w53edOFGCQ0g==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.css" integrity="sha512-BDStKWno6Ga+5cOFT9BUnl9erQFzfj+Qmr5MDnuGqTQ/QYDO1LPdonnF6V6lBO6JI13wg29/XmPsufxmCJ8TvQ==" crossorigin="anonymous" />

<script>
    // scroller active
    $('#dashboard_cbg').addClass('active');
    $('#vk').addClass('active');
    // pivot table js
    $(function(){
    $.getJSON("{% url 'monitoring:api_json_data_klaim_CBG_verifikator' %}", function(mps) {
        $("#output").pivotUI(mps,
            { rows: ["tgl_SLA", "faskes__nama", "register_klaim__nomor_register_klaim", "JNSPEL", "bupel", ], cols: ["verifikator__username", "status"] },
            false
        );
    });
 });
</script>
{% endblock %}

ilogic/templates/monitoring/monitoring_data_klaim_hitung_supervisor.html
{% extends 'base.html' %}

{% block content %}
<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card table-card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>Monitoring Hitung Data Klaim</h5>
        </div>
    <div id="output" style="margin: 30px;"></div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.js" integrity="sha512-XgJh9jgd6gAHu9PcRBBAp0Hda8Tg87zi09Q2639t0tQpFFQhGpeCgaiEFji36Ozijjx9agZxB0w53edOFGCQ0g==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.css" integrity="sha512-BDStKWno6Ga+5cOFT9BUnl9erQFzfj+Qmr5MDnuGqTQ/QYDO1LPdonnF6V6lBO6JI13wg29/XmPsufxmCJ8TvQ==" crossorigin="anonymous" />

<script>
    // scroller active
    $('#dashboard_cbg').addClass('active');
    $('#vk').addClass('active');
    // pivot table js
    $(function(){
    $.getJSON("{% url 'monitoring:api_json_data_klaim_hitung_supervisor' %}", function(mps) {
        $("#output").pivotUI(mps,
            { rows: ["tglhitung","periodehitung",], cols: ["jenis_klaim", "verifikator__username",] },
            false
        );
    });
 });
</script>
{% endblock %}