ilogic/faskes/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('register', views.register, name='register'),
    path('daftar-register', views.daftar_register, name='daftar-register'),
    path('detail-register/<int:pk>', views.detail_register, name='detail-register'),

    # cbg
    path('daftar/dataklaim/cbg/pending/dispute/', views.daftar_data_klaim_pending_dispute_cbg, name='daftar_data_klaim_pending_dispute_cbg'),
    path('detail/dataklaim/cbg/pending/dispute/<int:pk>/', views.detail_data_klaim_pending_dispute_cbg, name='detail_data_klaim_pending_dispute_cbg'),

    # obat
    path('daftar/dataklaim/obat/pending/dispute/', views.daftar_data_klaim_pending_dispute_obat, name='daftar_data_klaim_pending_dispute_obat'),
    path('detail/dataklaim/obat/pending/dispute/<int:pk>/', views.detail_data_klaim_pending_dispute_obat, name='detail_data_klaim_pending_dispute_obat'),

]

ilogic/supervisorkp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('api/json/monitoring/register/', views.api_json_register_supervisorkp, name='api_json_register_supervisorkp'),
    path('monitoring/register/', views.monitoring_register_supervisorkp, name='monitoring_register_supervisorkp'),
    path('manajemen/daftar/user/', views.daftar_user_supervisorkp, name='daftar_user_supervisorkp'),
    path('manajemen/edit/user/<int:pk>/', views.update_user_supervisorkp, name='update_user_supervisorkp'),
    path('manajemen/edit/<int:pk>/password/', views.reset_password_supervisorkp, name='reset_password_supervisorkp'),
    path('manajemen/add/user/', views.add_user_supervisorkp, name='add_user_supervisorkp'),
    path('data/klaim/cbg/', views.daftar_data_klaim_cbg, name='daftar_data_klaim_cbg'),
]

ilogic/user/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('ubahpassword', views.ubahpassword, name='ubahpassword'),
    path('logout', views.user_logout, name='logout'),

    path('new-user/', views.create_user_kantor_cabang, name='web_usr_add'),
    path('kanca/', include([
        path('user/change/group/<pk>/', views.change_group, name='kanca_grp_change'),
        path('user/group/add/kantorcabang', views.add_group, name='kanca_grp_add'),
        path('user/change/password/<pk>/', views.change_password, name='kanca_usr_passwd'),
        path('', views.user_per_kanca, name='kanca_user_list')
    ])),

    path('faskes/', include([
        path('', views.user_per_faskes, name='cbg_user_list')
    ])),

    path('new-user/faskes/', views.create_user_faskes, name='create_user_faskes'),

    path('list/verifikator/', views.user_per_verifikator, name='user_per_verifikator'),
    path('edit/active/verifikator/<int:pk>/', views.edit_user_verifikator_active, name='edit_user_verifikator_active'),
    path('edit/staff/verifikator/<int:pk>/', views.edit_user_verifikator_staff, name='edit_user_verifikator_staff'),
]

ilogic/viis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from user import views
from user.views import dashboard

admin.site.site_header = "BPJS Kesehatan"
admin.site.site_title = "BPJS Kesehatan"
admin.site.index_title = "Selamat Datang di Portal BPJS Kesehatan"

admin.site.login = views.user_login

urlpatterns = [
    path('admin/ilogic/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('faskes/', include(('faskes.urls', 'faskes'), namespace='faskes')),
    path('klaim/', include(('klaim.urls', 'klaim'), namespace='klaim')),
    path('verifikator/', include(('verifikator.urls', 'verifikator'), namespace='verifikator')),
    path('staff/', include(('staff.urls', 'staff'), namespace='staff')),
    path('captcha/', include('captcha.urls')),
    path('monitoring/', include(('monitoring.urls', 'monitoring'), namespace='monitoring')),
    path('supervisor/', include(('supervisor.urls', 'supervisor'), namespace='supervisor')),
    # path('dokumentasi/', include(('dokumentasi.urls', 'dokumentasi'), namespace='dokumentasi')),
    path('supervisorkp/', include(('supervisorkp.urls', 'supervisorkp'), namespace='supervisorkp')),
    path('vpkaak/', include(('vpkaak.urls', 'vpkaak'), namespace='vpkaak')),
    path('metafisik/', include(('metafisik.urls', 'metafisik'), namespace='metafisik')),


    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ilogic/klaim/models.py
from django.db import models

from datetime import datetime, timedelta, date

from django.utils.functional import cached_property

from faskes.models import Faskes, KantorCabang
from user.models import User
from verifikator.models import HitungDataKlaim
from .choices import (
    StatusRegisterChoices,
    JenisDisputeChoices,
    JenisPelayananChoices,
    StatusDataKlaimChoices, NamaJenisKlaimChoices, JenisPendingChoices, StatusSinkronChoices, StatusVidiChoices
)
from faskes.models import (
    Faskes
)


class JenisKlaim(models.Model):
    nama = models.CharField(max_length=250, choices=NamaJenisKlaimChoices.choices, unique=True)  # penambahan choices
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.nama}'


class SLA(models.Model):
    jenis_klaim = models.ForeignKey(JenisKlaim, on_delete=models.CASCADE)
    kantor_cabang = models.ForeignKey(KantorCabang, on_delete=models.CASCADE)
    plus_hari_sla = models.PositiveIntegerField(default=6)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.jenis_klaim} - {self.kantor_cabang} - {str(self.plus_hari_sla)}'


class RegisterKlaim(models.Model):
    nomor_register_klaim = models.CharField(max_length=250, unique=True)

    faskes = models.ForeignKey(Faskes, on_delete=models.CASCADE)
    jenis_klaim = models.ForeignKey(JenisKlaim, on_delete=models.CASCADE)
    verifikator = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    status = models.CharField(max_length=50,
                              choices=StatusRegisterChoices.choices, default=StatusRegisterChoices.PENGAJUAN)

    kasus_rawat_jalan_aju = models.PositiveBigIntegerField(default=0)
    biaya_rawat_jalan_aju = models.PositiveBigIntegerField(default=0)
    kasus_rawat_inap_aju = models.PositiveBigIntegerField(default=0)
    biaya_rawat_inap_aju = models.PositiveBigIntegerField(default=0)
    # kasus_rawat_jalan_lengkap = models.IntegerField(default=0)
    # biaya_rawat_jalan_lengkap = models.BigIntegerField(default=0)
    # kasus_rawat_inap_lengkap = models.IntegerField(default=0)
    # biaya_rawat_inap_lengkap = models.BigIntegerField(default=0)
    # kasus_rawat_jalan_verifikasi = models.IntegerField(default=0)
    # biaya_rawat_jalan_verifikasi = models.BigIntegerField(default=0)
    # kasus_rawat_inap_verifikasi = models.IntegerField(default=0)
    # biaya_rawat_inap_verifikasi = models.BigIntegerField(default=0)
    bulan_pelayanan = models.DateField()

    no_ba_terima = models.CharField(max_length=25, blank=True, null=True)
    no_ba_lengkap = models.CharField(max_length=25, blank=True, null=True)
    no_ba_hasil_verifikasi = models.CharField(max_length=25, blank=True, null=True)
    tgl_terima = models.DateField(blank=True, null=True)
    tgl_ba_lengkap = models.DateField(blank=True, null=True)
    tgl_ba_verif = models.DateField(blank=True, null=True)
    keterangan = models.CharField(max_length=50, blank=True, null=True)
    absensi_klaim = models.CharField(max_length=200, blank=True, null=True)
    tgl_aju = models.DateTimeField(blank=True, null=True) # ganti jadi date time
    nomor_surat_pengajuan_rs = models.CharField(max_length=50) # default nya di hapus saja
    is_final = models.BooleanField(default=False)
    prosesboa = models.BooleanField(default=False)
    tgl_boa = models.DateField(blank=True, null=True)
    is_potongklaim = models.BooleanField(default=False)
    keterangan_potongklaim = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    file_data_klaim = models.FileField(upload_to='data-klaim/', blank=True, null=True)

    is_pengajuan_ulang = models.BooleanField(default=False)     # Flaging pengajuan ulang data klaim pending/dispute.

    # dihapus karena ada faskes dan bulan pelayanan yang bisa diajukan sama
    # class Meta:
    #     unique_together = ['faskes', 'bulan_pelayanan']

    def __str__(self):
        return f'{self.nomor_register_klaim}'

    # @property
    # def data_klaim_total(self):

    # auto tgl ba lengkap
    def save(self, *args, **kwargs):
        if self.tgl_ba_lengkap is None:
            if self.tgl_terima:
                self.tgl_ba_lengkap = self.tgl_terima + timedelta(days=9)
        elif self.tgl_ba_lengkap > self.tgl_terima + timedelta(days=9):
            self.tgl_ba_lengkap = self.tgl_terima + timedelta(days=9)
        super(RegisterKlaim, self).save(*args, **kwargs)

    @cached_property
    def tgl_hari_ini(self):
        today = datetime.now()
        return today

    @cached_property
    def tgl_selesai_verif(self):
        return self.tgl_ba_lengkap + timedelta(days=9)

    @cached_property
    def tgl_jatuh_tempo(self):
        return self.tgl_ba_lengkap + timedelta(days=14)

    @cached_property
    def sisa_hari(self):
        return self.tgl_selesai_verif - self.tgl_hari_ini

    @cached_property
    def tgl_ba_lengkap_seharusnya(self):
        if self.tgl_terima:
            return self.tgl_terima + timedelta(days=9)
        elif self.tgl_aju:
            return self.tgl_aju + timedelta(days=9)

    @cached_property
    def sisa_klaim(self):
        sisa_klaim = 0
        if self.jenis_klaim.nama == NamaJenisKlaimChoices.CBG_REGULER or self.jenis_klaim.nama == NamaJenisKlaimChoices.CBG_SUSULAN:
            data_klaim = DataKlaimCBG.objects.filter(register_klaim__nomor_register_klaim=self.nomor_register_klaim,
                                                     status=StatusDataKlaimChoices.PROSES)
            sisa_klaim = data_klaim.count()
        elif self.jenis_klaim.nama == NamaJenisKlaimChoices.OBAT_REGULER or self.jenis_klaim.nama == NamaJenisKlaimChoices.OBAT_SUSULAN:
            data_klaim = DataKlaimObat.objects.filter(register_klaim__nomor_register_klaim=self.nomor_register_klaim,
                                                      status=StatusDataKlaimChoices.PROSES)
            sisa_klaim = data_klaim.count()
        return sisa_klaim


    @classmethod
    def generate_kode_register(cls, faskes):
        kantor_cabang = faskes.kantor_cabang
        queryset = cls.objects.filter(faskes__kantor_cabang=kantor_cabang)
        if queryset.count() != 0:
            last_nomor = cls.objects.filter(faskes__kantor_cabang=kantor_cabang).last().nomor_register_klaim
        else:
            current_time = datetime.now()
            new_last_nomor = f'{kantor_cabang.kode_cabang}{str(current_time.year)[2:]}{str(current_time.month).zfill(2)}0001'
            return new_last_nomor

        year = int(last_nomor[4:6])
        month = int(last_nomor[6:8])
        increment = last_nomor[8:]

        current_year = datetime.now().year
        current_year = str(current_year)[2:]
        current_month = datetime.now().month
        if int(current_month) != int(month) or int(current_year) != int(year):
            increment = '1'.zfill(4)
        else:
            increment = int(increment)
            increment += 1
            increment = str(increment).zfill(4)

        new_last_nomor = f'{kantor_cabang.kode_cabang}{current_year}{str(current_month).zfill(2)}{increment}'

        if cls.objects.filter(nomor_register_klaim=new_last_nomor).exists():
            return cls.generate_kode_register(faskes=faskes)
        return new_last_nomor


class KeteranganPendingDispute(models.Model):
    ket_pending_dispute = models.CharField(max_length=1000)
    verifikator = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ket_pending_dispute


class JawabanPendingDispute(models.Model):
    ket_jawaban_pending = models.CharField(max_length=1000)
    user_faskes = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ket_jawaban_pending


class DataKlaimCBG(models.Model):
    register_klaim = models.ForeignKey(RegisterKlaim, on_delete=models.CASCADE)
    faskes = models.ForeignKey(Faskes, on_delete=models.CASCADE)
    verifikator = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    bupel = models.DateField(blank=True, null=True)
    tgl_SLA = models.DateField(blank=True, null=True)
    ALGORITMA = models.CharField(max_length=1000, blank=True, null=True)
    status = models.CharField(max_length=200,
                              default=StatusDataKlaimChoices.BELUM_VER, choices=StatusDataKlaimChoices.choices)
    NOSEP = models.CharField(max_length=200, blank=True, null=True, unique=True)
    TGLSEP = models.DateField(blank=True, null=True)
    TGLPULANG = models.DateField(blank=True, null=True)
    JNSPEL = models.CharField(max_length=200, blank=True, null=True, choices=JenisPelayananChoices.choices)
    NOKARTU = models.CharField(max_length=200, blank=True, null=True)
    NMPESERTA = models.CharField(max_length=200, blank=True, null=True)
    POLI = models.CharField(max_length=200, blank=True, null=True)
    KDINACBG = models.CharField(max_length=200, blank=True, null=True)
    BYPENGAJUAN = models.PositiveBigIntegerField(default=0)
    ket_pending_dispute = models.ManyToManyField(KeteranganPendingDispute)
    ket_jawaban_pending = models.ManyToManyField(JawabanPendingDispute)
    # ket_pending_dispute = models.CharField(max_length=500, blank=True, null=True)
    # ket_jawaban_pending = models.CharField(max_length=500, blank=True, null=True)

    prosesklaim = models.BooleanField(default=False)
    prosespending = models.BooleanField(default=False)
    prosesdispute = models.BooleanField(default=False)

ilogic/supervisorkp/models.py
from django.db import models

# Create your models here.

ilogic/staff/forms.py
import datetime

from django import forms
from django.forms import SelectDateWidget

from klaim.models import (
    RegisterKlaim,
    JenisKlaim
)
from user.models import User

STATUS_CHOICES_TERIMA_REGISTER_STAFAK = (
    ('Terima', 'Terima'),
    ('Dikembalikan', 'Dikembalikan'),
)


class DateInputMaxToday(forms.DateInput):
    input_type = 'date'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.attrs.setdefault('max', datetime.date.today())


class StatusRegisterKlaimForm(forms.ModelForm):
    status = forms.ChoiceField(choices=STATUS_CHOICES_TERIMA_REGISTER_STAFAK)
    tgl_terima = forms.DateField(widget=DateInputMaxToday, required=False)
    no_ba_terima = forms.CharField(required=False, min_length=5)
    verifikator = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    keterangan = forms.CharField(min_length=5, required=False)

    class Meta:
        model = RegisterKlaim
        fields = ['status',
                  'tgl_terima',
                  'no_ba_terima',
                  'verifikator',
                  'keterangan']


class PilihVerifikatorRegisterKlaimForm(forms.ModelForm):
    tgl_terima = forms.DateField(widget=DateInputMaxToday, required=True)
    no_ba_terima = forms.CharField(required=True, min_length=5)
    verifikator = forms.ModelChoiceField(queryset=User.objects.all(), required=True)

    class Meta:
        model = RegisterKlaim
        fields = ['tgl_terima', 'no_ba_terima', 'verifikator']


class AlasanDikembalikanForm(forms.ModelForm):
    keterangan = forms.CharField(min_length=5, required=True)

    class Meta:
        model = RegisterKlaim
        fields = ['keterangan']


class IsActiveForm(forms.ModelForm):
    is_staff = forms.BooleanField(label="Verifikator Aktif", required=False,
                                  help_text="Jika Ter-Checklist, maka Verifikator masih bisa login dan "
                                            "melakukan verifikasi, namun tidak dapat menjadi PIC dan pembagian klaim.")

    class Meta:
        model = User
        fields = ['is_staff']


class ProsesBOAForm(forms.ModelForm):
    tgl_boa = forms.DateField(widget=DateInputMaxToday, required=True)
    class Meta:
        model = RegisterKlaim
        fields = ['tgl_boa']

ilogic/templates/supervisorkp/daftar_data_klaim_cbg.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load my_tags %}

{% block content %}

<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>
                Data Klaim  <span class="badge bg-danger">{{ request.count_data_klaim }}</span>
            </h5>
            <form>
                    <button type="submit" class="btn btn-primary" name="export" value="export"><i class="fas fa-file-download"><span style="font-size: 15px"> Download</span></i></button>
            </form>
        </div>

        <div class="card-body">
              <form class="row row-cols-md-auto g-3 align-items-center">
{#                <div class="col-12">#}
{#                  <label class="sr-only" for="id_status">JNSPEL</label>#}
{#                  <select class="form-select" name="JNSPEL" id="id_JNSPEL">#}
{#                      <option selected value="">JNSPEL...</option>#}
{#                      <option value="Rawat Inap" {% if request.GET.JNSPEL == 'Rawat Inap' %}selected {% endif %}>Rawat Inap</option>#}
{#                      <option value="Rawat Jalan" {% if request.GET.JNSPEL == 'Rawat Jalan' %}selected {% endif %}>Rawat Jalan</option>#}
{#                  </select>#}
{#                </div>#}
{#                <div class="col-12">#}
{#                  <label class="sr-only" for="id_status">Status</label>#}
{#                  <select class="form-select" name="status" id="id_status">#}
{#                      <option selected value="">Status...</option>#}
{#                      <option value="Pending" {% if request.GET.status == 'Pending' %}selected {% endif %}>Pending</option>#}
{#                      <option value="Dispute" {% if request.GET.status == 'Dispute' %}selected {% endif %}>Dispute</option>#}
{#                      <option value="Pembahasan" {% if request.GET.status == 'Pembahasan' %}selected {% endif %}>Pembahasan</option>#}
{#                  </select>#}
{#                </div>#}
                  {{ myFilter.form | crispy }}
                <div class="col-12">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
        </div>
{#        <form>#}
{#          <div class="form-row align-items-center container-fluid">#}
{#            <div class="col-auto my-1">#}
{#              {{myFilter.form.namars }}#}
{#            </div>#}
{#            {{ myFilter.form.media }}#}
{#            <div class="col-auto my-1">#}
{#                <select class="custom-select mr-sm-2" name="Status" id="id_Status">#}
{#                  <option selected value="">Status...</option>#}
{#                  <option value="Proses" {% if request.GET.Status == 'Proses' %}selected {% endif %}>Proses</option>#}
{#                  <option value="Layak" {% if request.GET.Status == 'Layak' %}selected {% endif %}>Layak</option>#}
{#                  <option value="Pending" {% if request.GET.Status == 'Pending' %}selected {% endif %}>Pending</option>#}
{#                  <option value="Dispute" {% if request.GET.Status == 'Dispute' %}selected {% endif %}>Dispute</option>#}
{#                  <option value="Tidak Layak" {% if request.GET.Status == 'Tidak Layak' %}selected {% endif %}>Tidak Layak</option>#}
{#                </select>#}
{#            </div>#}
{##}
{#            <div class="col-auto my-1">#}
{#              <button type="submit" class="" name="export" value="export"><img src="https://img.icons8.com/color/32/000000/export-excel.png"/></button>#}
{#            </div>#}
{#          </div>#}
{#        </form>#}
        <div class="table-responsive">
                <table class="table table-xs table-hover table-borderless mb-0" id="data-table">
                    <thead>
                        <tr>
                            <th scope="col">Status</th>
                            <th scope="col">RS</th>
                            <th scope="col">No REG</th>
                            <th scope="col">No SEP</th>
                            <th scope="col">In</th>
                            <th scope="col">Out</th>
                            <th scope="col">Jns Pel</th>
                            <th scope="col">No Kartu</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Poli</th>
                            <th scope="col">CBG</th>
                            <th scope="col">Biaya</th>
{#                            <th scope="col">Ket. Pending</th>#}
{#                            <th scope="col">Jawaban</th>#}
                        </tr>
                    </thead>
                    <tbody>
                    {% for data_klaim in data_klaim %}
                    <tr>
                        <td>
                            {% if data_klaim.status == 'Pending' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_cbg' data_klaim.id %}?next={{ request.get_full_path|urlencode }}">
                                    <button type="button" class="btn btn-warning btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Dispute' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_cbg' data_klaim.id %}?next={{ request.get_full_path|urlencode }}">
                                    <button type="button" class="btn btn-dark btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Pembahasan' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_cbg' data_klaim.id %}?next={{ request.path|urlencode }}">
                                    <button type="button" class="btn btn-info btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Tidak Layak' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_cbg' data_klaim.id %}?next={{ request.path|urlencode }}">
                                    <button type="button" class="btn btn-danger btn-sm">{{ data_klaim.status }}</button>
                            {% endif %}
                        </td>
                        <td>{{data_klaim.faskes.nama}}</td>
                        <td>{{data_klaim.register_klaim.nomor_register_klaim}}</td>
                        <td>{{data_klaim.NOSEP}}</td>
                        <td>{{data_klaim.TGLSEP}}</td>
                        <td>{{data_klaim.TGLPULANG}}</td>
                        <td>{{data_klaim.JNSPEL}}</td>
                        <td>{{data_klaim.NOKARTU}}</td>
                        <td>{{data_klaim.NMPESERTA}}</td>
                        <td>{{data_klaim.bupel|date:'M-y'}}</td>
                        <td>{{data_klaim.KDINACBG}}</td>
                        <td>{{data_klaim.BYPENGAJUAN}}</td>
{#                        <td>{{data_klaim.ket_pending_dispute}}</td>#}
{#                        <td>{{data_klaim.ket_jawaban_pending}}</td>#}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<!-- Pagination -->
<div class="pagination justify-content-center">
    <span class="step-links">
        {% if data_klaim.has_previous %}
            <a href="?{% param_replace page=1 %}">&laquo; First</a>
            {% if data_klaim.previous_page_number != 1 %}
            <a href="?{% param_replace page=data_klaim.previous_page_number %}">Previous</a>
            {% endif %}
        {% endif %}

        Page {{ data_klaim.number }} of {{ data_klaim.paginator.num_pages }}

        {% if data_klaim.has_next %}
            {% if data_klaim.next_page_number != paginator.num_pages %}
            <a href="?{% param_replace page=data_klaim.next_page_number %}">Next</a>
            {% endif %}
            <a href="?{% param_replace page=data_klaim.paginator.num_pages %}">Last &raquo;</a>
        {% endif %}
        <p>Data Klaim {{ data_klaim.start_index }} - {{ data_klaim.end_index }} </p>
    </span>
</div>

{#<script>#}
{#    var search = ''#}
{#    var status = ''#}
{#    var grid = new gridjs.Grid({#}
{#        columns: ["DETAIL", "NOSEP", "NOKARTU", "NMPESERTA", "BUPEL", "STATUS", "FASKES"],#}
{#        pagination: {#}
{#            limit: 10,#}
{#            server: {#}
{#                url: (prev, page, limit) => `${prev}?limit=${limit}&offset=${page * limit}&search=${search}&status=${status}`#}
{#            }#}
{#        },#}
{#        server: {#}
{#            url: '/verifikator/api/data-klaim',#}
{#            then: data => data.results.map(data =>#}
{#                [ gridjs.html(`<a href="/verifikator/detail-data-klaim/${data.id}" class="btn btn-primary">DETAIL</a>`), data.NOSEP, data.NOKARTU, data.NMPESERTA, data.bupel, data.status, data.faskes]#}
{#                ),#}
{#            total: data => data.count#}
{#            }#}
{#   })#}
{#   grid.render(document.getElementById("data-klaim"))#}
{##}
{#   document.getElementById("input-search").addEventListener("input", function(e){#}
{#    search = e.target.value#}
{#    grid.updateConfig({#}
{#    }).forceRender()#}
{#   })#}
{##}
{#   document.getElementById("input-status").addEventListener("input", function(e){#}
{#    status = e.target.value#}
{#    grid.updateConfig({#}
{#    }).forceRender()#}
{#   })#}
{##}
{##}
{##}
{#</script>#}
{% endblock %}

ilogic/templates/supervisorkp/monitoring_register_supervisorkp.html
{% extends 'base.html' %}

{% block content %}
<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card table-card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>Monitoring Register VIBI</h5>
        </div>
    <div id="output" style="margin: 30px;"></div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.js" integrity="sha512-XgJh9jgd6gAHu9PcRBBAp0Hda8Tg87zi09Q2639t0tQpFFQhGpeCgaiEFji36Ozijjx9agZxB0w53edOFGCQ0g==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.css" integrity="sha512-BDStKWno6Ga+5cOFT9BUnl9erQFzfj+Qmr5MDnuGqTQ/QYDO1LPdonnF6V6lBO6JI13wg29/XmPsufxmCJ8TvQ==" crossorigin="anonymous" />

<script>
    // scroller active
    $('#dashboard_cbg').addClass('active');
    $('#vk').addClass('active');
    // pivot table js
    $(function(){
    $.getJSON("{% url 'supervisorkp:api_json_register_supervisorkp' %}", function(mps) {
        $("#output").pivotUI(mps,
            { rows: ["faskes__kantor_cabang__nama", "faskes__nama"], cols: ["bulan_pelayanan"] },
            false
        );
    });
 });
</script>
{% endblock %}