ilogic/user/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('ubahpassword', views.ubahpassword, name='ubahpassword'),
    path('logout', views.user_logout, name='logout'),

    path('new-user/', views.create_user_kantor_cabang, name='web_usr_add'),
    path('kanca/', include([
        path('user/change/group/<pk>/', views.change_group, name='kanca_grp_change'),
        path('user/group/add/kantorcabang', views.add_group, name='kanca_grp_add'),
        path('user/change/password/<pk>/', views.change_password, name='kanca_usr_passwd'),
        path('', views.user_per_kanca, name='kanca_user_list')
    ])),

    path('faskes/', include([
        path('', views.user_per_faskes, name='cbg_user_list')
    ])),

    path('new-user/faskes/', views.create_user_faskes, name='create_user_faskes'),

    path('list/verifikator/', views.user_per_verifikator, name='user_per_verifikator'),
    path('edit/active/verifikator/<int:pk>/', views.edit_user_verifikator_active, name='edit_user_verifikator_active'),
    path('edit/staff/verifikator/<int:pk>/', views.edit_user_verifikator_staff, name='edit_user_verifikator_staff'),
]

ilogic/viis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from user import views
from user.views import dashboard

admin.site.site_header = "BPJS Kesehatan"
admin.site.site_title = "BPJS Kesehatan"
admin.site.index_title = "Selamat Datang di Portal BPJS Kesehatan"

admin.site.login = views.user_login

urlpatterns = [
    path('admin/ilogic/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('faskes/', include(('faskes.urls', 'faskes'), namespace='faskes')),
    path('klaim/', include(('klaim.urls', 'klaim'), namespace='klaim')),
    path('verifikator/', include(('verifikator.urls', 'verifikator'), namespace='verifikator')),
    path('staff/', include(('staff.urls', 'staff'), namespace='staff')),
    path('captcha/', include('captcha.urls')),
    path('monitoring/', include(('monitoring.urls', 'monitoring'), namespace='monitoring')),
    path('supervisor/', include(('supervisor.urls', 'supervisor'), namespace='supervisor')),
    # path('dokumentasi/', include(('dokumentasi.urls', 'dokumentasi'), namespace='dokumentasi')),
    path('supervisorkp/', include(('supervisorkp.urls', 'supervisorkp'), namespace='supervisorkp')),
    path('vpkaak/', include(('vpkaak.urls', 'vpkaak'), namespace='vpkaak')),
    path('metafisik/', include(('metafisik.urls', 'metafisik'), namespace='metafisik')),


    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ilogic/vpkaak/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from . import views, api_views
from .cekgroupingfix import query_icd10, query_icd9, grouping
from .views import cek_grouping, is_bayi

router = SimpleRouter(trailing_slash=False)
router.register('api/register/', api_views.RegisterPostKlaimViewSet, basename='api-register-vpkaak')
router.register('api/register/supervisorkp', api_views.RegisterPostKlaimSupervisorKPViewSet, basename='api-register-vpkaak-supervisorkp')


urlpatterns = [
    path('register', views.register_post_klaim, name='register-post-klaim'),
    path('import-sampling-data-klaim', views.import_sampling_data_klaim, name='import-sampling-data-klaim'),
    path('review/post-klaim', views.review, name='review-post-klaim'),
    path('update/review/<int:pk>', views.update_review, name='update-review'),
    path('finalisasi/register/post-klaim', views.finalisasi_register_post_klaim, name='finalisasi-register-post-klaim'),
    path('update/finalisasi/register/post-klaim/<int:pk>', views.update_finalisasi_register_post_klaim, name='update-finalisasi-register-post-klaim'),
    path('kertas-kerja-verifikasi', views.kertas_kerja_koreksi, name='kertas-kerja-koreksi'),
    path('input-nomor-ba/<int:pk>', views.input_nomor_ba, name='input-nomor-ba'),

    # review dari data kp
    path('review/post-klaim/kp', views.reviewkp, name='review_post_klaim_kp'),
    path('update/review/kp/<int:pk>', views.update_review_kp, name='update_review_kp'),

    # grouping
    path('query_icd10/', query_icd10, name='query_icd10'),
    path('query_icd9/', query_icd9, name='query_icd9'),
    path('cek_grouping/', cek_grouping, name='cek_grouping'),
    path('is_bayi/', is_bayi, name='is_bayi'),

    # supervisorkp
    path('register/supervisorkp', views.register_post_klaim_supervisorkp, name='register_post_klaim_supervisorkp'),
    path('import-sampling-data-klaim/supervisorkp', views.import_sampling_data_klaim_supervisorkp, name='import_sampling_data_klaim_supervisorkp'),
    path('finalisasi/register/post-klaim/KP', views.finalisasi_register_post_klaim_supervisorkp, name='finalisasi_register_post_klaim_supervisorkp'),
    path('update/finalisasi/register/post-klaim/KP/<int:pk>', views.update_finalisasi_register_post_klaim_supervisorkp, name='update_finalisasi_register_post_klaim_supervisorkp'),

    # monitoring
    path('api/json/monitoring/data/sampling/vpkaak', views.api_json_data_sampling_vpkaak, name='api_json_data_sampling_vpkaak'),
    path('monitoring/data/sampling/vpkaak', views.monitoring_data_sampling_vpkaak, name='monitoring_data_sampling_vpkaak'),

    path('api/json/monitoring/data/sampling/vpkaak/KP', views.api_json_data_sampling_vpkaak_supervisorkp, name='api_json_data_sampling_vpkaak_supervisorkp'),
    path('monitoring/data/sampling/vpkaak/KP', views.monitoring_data_sampling_vpkaak_supervisorkp, name='monitoring_data_sampling_vpkaak_supervisorkp'),

    # rpa
    path('rpa/cbg', views.rpa_cbg_vpkaak, name='rpa_cbg_vpkaak'),

              ] + router.urls

ilogic/vpkaak/models.py
from django.db import models
from django.db.models import Max
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone
from django.core.validators import MinLengthValidator

from faskes.models import Faskes
from vpkaak.choices import JenisAuditChoices, KelasFaskesChoices, StatusChoices, InisiasiChoices, StatusReviewChoices
from user.models import User


# Create your models here.
class RegisterPostKlaim(models.Model):
    nomor_register = models.CharField(max_length=255, blank=True, null=True)
    jenis_audit = models.CharField(max_length=10, choices=JenisAuditChoices.choices)
    status = models.CharField(max_length=50, choices=StatusChoices.choices, blank=True, null=True)
    nomor_BA_VPK_AAK = models.CharField(max_length=255, null=True, blank=True)
    tanggal_BA_VPK_AAK = models.DateField(null=True, blank=True)
    is_final = models.BooleanField(default=False)
    tanggal_final = models.DateField(null=True, blank=True)
    biaya_efisiensi = models.IntegerField(null=True, blank=True)
    # AAK
    inisiasi = models.CharField(max_length=255, choices=InisiasiChoices.choices, null=True, blank=True)
    periode_awal = models.DateField(null=True, blank=True)
    periode_akhir = models.DateField(null=True, blank=True)
    surat_tugas = models.CharField(max_length=255, null=True, blank=True)
    # VPK
    bulan_beban = models.DateField(null=True, blank=True)
    # staff_upk = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="staff_upk")
    # verifikator = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="verifikator")
    # faskes = models.ForeignKey(Faskes, on_delete=models.CASCADE, null=True, blank=True, related_name="faskes")
    # kelas = models.CharField(max_length=10, choices=KelasFaskesChoices.choices, blank=True, null=True)

    is_kp = models.BooleanField(default=False)
    # is_from_kp = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="user_register")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nomor_register


# @receiver(pre_save, sender=RegisterPostKlaim)
# def generate_nama_register(sender, instance, **kwargs):
#     if not instance.nomor_register_klaim:
#         if instance.jenis_audit == 'AAK-FKRTL':
#             jenis_audit_prefix = 'AAK-FKRTL'
#         elif instance.jenis_audit == 'VPK-FKRTL':
#             jenis_audit_prefix = 'VPK-FKRTL'
#         else:
#             jenis_audit_prefix = 'OTHER'
#         bulan_tahun = timezone.now().strftime("%m%y")
#         max_nomor_urut = RegisterPostKlaim.objects.filter(
#             nomor_register_klaim__startswith=f"001/{jenis_audit_prefix}/{instance.user.kantor_cabang.kode_cabang}/{bulan_tahun}"
#         ).aggregate(Max('nomor_register_klaim'))
#         if max_nomor_urut['nomor_register_klaim__max']:
#             nomor_urut = int(max_nomor_urut['nomor_register_klaim__max'].split('/')[0])
#             nomor_urut += 1
#         else:
#             nomor_urut = 1
#
#         instance.nomor_register_klaim = f"{nomor_urut:03d}/{jenis_audit_prefix}/{instance.user.kantor_cabang.kode_cabang}/{bulan_tahun}"


class SamplingDataKlaimCBG(models.Model):
    register = models.ForeignKey(RegisterPostKlaim, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=StatusReviewChoices.choices, default="Belum Review")

    # dataklaimcbg
    Nokapst = models.CharField(max_length=255)
    Tgldtgsjp = models.DateField()
    Tglplgsjp = models.DateField()
    Nosjp = models.CharField(max_length=255)
    Tglpelayanan = models.DateField()
    Kdkrlayan = models.CharField(max_length=255)
    Kdkclayan = models.CharField(max_length=255, validators=[MinLengthValidator(4)])
    Nmkclayan = models.CharField(max_length=255)
    Kddati2Layan = models.CharField(max_length=255)
    Nmdati2Layan = models.CharField(max_length=255)
    Kdppklayan = models.CharField(max_length=255)
    Nmppklayan = models.CharField(max_length=255)
    Nmtkp = models.CharField(max_length=255)
    Kdinacbgs = models.CharField(max_length=255)
    Nminacbgs = models.CharField(max_length=255)
    Kddiagprimer = models.CharField(max_length=255)
    Nmdiagprimer = models.CharField(max_length=255)
    Diagsekunder = models.CharField(max_length=5000, blank=True, null=True)
    Procedure = models.CharField(max_length=5000, blank=True, null=True)
    Klsrawat = models.CharField(max_length=255)
    Nmjnspulang = models.CharField(max_length=255)
    kddokter = models.CharField(max_length=255, blank=True, null=True)
    nmdokter = models.CharField(max_length=255, blank=True, null=True)
    Umur = models.IntegerField()
    Jkpst = models.CharField(max_length=10, blank=True, null=True)
    kdsa = models.CharField(max_length=255)
    kdsd = models.CharField(max_length=255)
    deskripsisd = models.CharField(max_length=255, default='-', blank=True, null=True)
    kdsi = models.CharField(max_length=255)
    deskripsisi = models.CharField(max_length=255, default='-', blank=True, null=True)
    kdsp = models.CharField(max_length=255)
    deskripsisp = models.CharField(max_length=255, default='-', blank=True, null=True)
    kdsr = models.CharField(max_length=255)
    deskripsisr = models.CharField(max_length=255)
    Tarifgroup = models.IntegerField()
    tarifsa = models.IntegerField()
    tarifsd = models.IntegerField()
    tarifsi = models.IntegerField()
    tarifsp = models.IntegerField()
    tarifsr = models.IntegerField()
    Biayaverifikasi = models.IntegerField()
    redflag = models.CharField(max_length=500, blank=True, null=True)
    deskripsi_redflag = models.CharField(max_length=1000, blank=True, null=True)
    source = models.CharField(max_length=100, blank=True, null=True)

    # databayi
    is_bayi = models.BooleanField(default=False)
    beratbayi = models.IntegerField(default=0)
    tanggallahirbayi = models.DateField(blank=True, null=True)

    # datars
    Kodersmenkes = models.CharField(max_length=15, blank=True, null=True)
    Kelasrsmenkes = models.CharField(max_length=10, blank=True, null=True)

    # hasil koreksi
    is_koreksi = models.BooleanField(default=False)
    Kddiagprimer_koreksi = models.CharField(max_length=5000, blank=True, null=True)
    Nmdiagprimer_koreksi = models.CharField(max_length=5000, blank=True, null=True)
    Diagsekunder_koreksi = models.CharField(max_length=5000, blank=True, null=True)
    Procedure_koreksi = models.CharField(max_length=5000, blank=True, null=True)
    kdsa_koreksi = models.CharField(max_length=255, blank=True, null=True)
    kdsd_koreksi = models.CharField(max_length=255, blank=True, null=True)
    kdsi_koreksi = models.CharField(max_length=255, blank=True, null=True)
    kdsp_koreksi = models.CharField(max_length=255, blank=True, null=True)
    kdsr_koreksi = models.CharField(max_length=255, blank=True, null=True)
    Nmtkp_koreksi = models.CharField(max_length=255, blank=True, null=True)
    Kdinacbgs_koreksi = models.CharField(max_length=255, blank=True, null=True)
    Nminacbgs_koreksi = models.CharField(max_length=255, blank=True, null=True)
    Klsrawat_koreksi = models.CharField(max_length=255, blank=True, null=True)
    biaya_koreksi = models.IntegerField(blank=True, null=True)

    # review
    tgl_review = models.DateTimeField(blank=True, null=True)
    verifikator_review = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    keterangan_review = models.CharField(max_length=1000, blank=True, null=True, validators=[MinLengthValidator(10)])

    # identity
    is_from_kp = models.BooleanField(default=False)
    is_final = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # jenis fraud
    jenis_fraud = models.CharField(max_length=255, blank=True, null=True)
    # jenis_fraud = models.CharField(max_length=255, default='Temuan Administrasi yang tidak sesuai atau alasan lain yang bukan potensi fraud')

    # status koreksi BOA
    keterangan_koreksi_boa = models.CharField(max_length=255, blank=True, null=True)
    status_koreksi_boa = models.CharField(max_length=255, default='Belum Koreksi BOA')
    tgl_koreksi_boa = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'{self.Nosjp} - {self.register.nomor_register}'


class CookiesICD(models.Model):
    cookie_value = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.cookie_value

ilogic/templates/vpkaak/finalisasi_register_post_klaim.html
{% extends 'base.html' %}
{% load my_tags %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-xl-12 col-md-12 mb-4 mt-4">
        <div class="card table-card">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5>
                    Daftar Finalisasi Register Post Klaim (VPK-AAK)
{#                    <span class="badge bg-danger">{{ request.count_finalisasi }}</span>#}
                </h5>
            </div>

            <div class="container">
                <br>
                <div class="card-body">
                    <form class="row row-cols-md-auto g-3 align-items-center">
                        {{ myFilter.form | crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>


                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-borderless mb-0">
                            <thead>
                            <tr>
                                <th scope="col">Final</th>
                                <th scope="col">No Register</th>
                                <th scope="col">Tgl Register</th>
                                <th scope="col">Jenis Audit</th>
                                <th scope="col">Status</th>
                                <th scope="col">Periode</th>
                                <th scope="col">Bulan Beban</th>
                                {#                                <th scope="col">Biaya Register</th>#}
                                {#                                <th scope="col">Biaya Koreksi</th>#}
                                {#                                <th scope="col">Efisiensi</th>#}

                            </tr>
                            </thead>
                            <tbody>
                            {% for register in register_list %}
                                <tr>
                                    <td>
                                        <a href="{% url 'vpkaak:update-finalisasi-register-post-klaim' register.id %}">
                                            <button class="btn btn-success btn-sm">Final</button>
                                        </a>
                                    </td>
                                    <td>{{ register.nomor_register }}</td>
                                    <td>{{ register.created_at|date:"d/m/Y" }}</td>
                                    <td>{{ register.get_jenis_audit_display }}</td>
                                    {% if register.get_status_display == 'Register' %}
                                        <td>
                                            <buttton
                                                    class="btn btn-light btn-sm">{{ register.get_status_display }}</buttton>
                                        </td>
                                    {% elif register.get_status_display == 'Proses Review' %}
                                        <td>
                                            <buttton
                                                    class="btn btn-danger btn-sm">{{ register.get_status_display }}</buttton>
                                        </td>
                                    {% elif register.get_status_display == 'Selesai' %}
                                        <td>
                                            <buttton
                                                    class="btn btn-success btn-sm ">{{ register.get_status_display }}</buttton>
                                        </td>
                                    {% endif %}
                                    <td>{{ register.periode_awal|date:"d/m/Y"|default:"-" }}
                                        sd {{ register.periode_akhir|date:"d/m/Y"|default:"-" }}</td>
                                    <td>{{ register.bulan_beban|date:"M-y"|default:"-" }}</td>
                                    {#                                    <td></td>#}
                                    {#                                    <td></td>#}
                                    {#                                    <td></td>#}

                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">Tidak ada data</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pagination -->
        <div class="pagination justify-content-center">
    <span class="step-links">
        {% if register_list.has_previous %}
            <a href="?{% param_replace page=1 %}">&laquo; First</a>
            {% if register_list.previous_page_number != 1 %}
                <a href="?{% param_replace page=register_list.previous_page_number %}">Previous</a>
            {% endif %}
        {% endif %}

        Page {{ register_list.number }} of {{ register_list.paginator.num_pages }}

        {% if register_list.has_next %}
            {% if register_list.next_page_number != paginator.num_pages %}
                <a href="?{% param_replace page=register_list.next_page_number %}">Next</a>
            {% endif %}
            <a href="?{% param_replace page=register_list.paginator.num_pages %}">Last &raquo;</a>
        {% endif %}
        <p>Register Klaim {{ register_list.start_index }} - {{ register_list.end_index }} </p>
    </span>
        </div>
    </div>
{% endblock %}

ilogic/templates/vpkaak/finalisasi_register_post_klaim_supervisorkp.html
{% extends 'base.html' %}
{% load my_tags %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-xl-12 col-md-12 mb-4 mt-4">
        <div class="card table-card">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5>
                    Daftar Finalisasi Register Post Klaim KP (VPK-AAK)
{#                    <span class="badge bg-danger">{{ request.count_finalisasi }}</span>#}
                </h5>
            </div>

            <div class="container">
                <br>
                <div class="card-body">
                    <form class="row row-cols-md-auto g-3 align-items-center">
                        {{ myFilter.form | crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>


                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-borderless mb-0">
                            <thead>
                            <tr>
                                <th scope="col">Final</th>
                                <th scope="col">No Register</th>
                                <th scope="col">Tgl Register</th>
                                <th scope="col">Jenis Audit</th>
                                <th scope="col">Status</th>
                                <th scope="col">Periode</th>
                                <th scope="col">Bulan Beban</th>
                                {#                                <th scope="col">Biaya Register</th>#}
                                {#                                <th scope="col">Biaya Koreksi</th>#}
                                {#                                <th scope="col">Efisiensi</th>#}

                            </tr>
                            </thead>
                            <tbody>
                            {% for register in register_list %}
                                <tr>
                                    <td>
                                        <a href="{% url 'vpkaak:update_finalisasi_register_post_klaim_supervisorkp' register.id %}">
                                            <button class="btn btn-success btn-sm">Final</button>
                                        </a>
                                    </td>
                                    <td>{{ register.nomor_register }}</td>
                                    <td>{{ register.created_at|date:"d/m/Y" }}</td>
                                    <td>{{ register.get_jenis_audit_display }}</td>
                                    {% if register.get_status_display == 'Register' %}
                                        <td>
                                            <buttton
                                                    class="btn btn-light btn-sm">{{ register.get_status_display }}</buttton>
                                        </td>
                                    {% elif register.get_status_display == 'Proses Review' %}
                                        <td>
                                            <buttton
                                                    class="btn btn-danger btn-sm">{{ register.get_status_display }}</buttton>
                                        </td>
                                    {% elif register.get_status_display == 'Selesai' %}
                                        <td>
                                            <buttton
                                                    class="btn btn-success btn-sm ">{{ register.get_status_display }}</buttton>
                                        </td>
                                    {% endif %}
                                    <td>{{ register.periode_awal|date:"d/m/Y"|default:"-" }}
                                        sd {{ register.periode_akhir|date:"d/m/Y"|default:"-" }}</td>
                                    <td>{{ register.bulan_beban|date:"M-y"|default:"-" }}</td>
                                    {#                                    <td></td>#}
                                    {#                                    <td></td>#}
                                    {#                                    <td></td>#}

                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">Tidak ada data</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pagination -->
        <div class="pagination justify-content-center">
    <span class="step-links">
        {% if register_list.has_previous %}
            <a href="?{% param_replace page=1 %}">&laquo; First</a>
            {% if register_list.previous_page_number != 1 %}
                <a href="?{% param_replace page=register_list.previous_page_number %}">Previous</a>
            {% endif %}
        {% endif %}

        Page {{ register_list.number }} of {{ register_list.paginator.num_pages }}

        {% if register_list.has_next %}
            {% if register_list.next_page_number != paginator.num_pages %}
                <a href="?{% param_replace page=register_list.next_page_number %}">Next</a>
            {% endif %}
            <a href="?{% param_replace page=register_list.paginator.num_pages %}">Last &raquo;</a>
        {% endif %}
        <p>Register Klaim {{ register_list.start_index }} - {{ register_list.end_index }} </p>
    </span>
        </div>
    </div>
{% endblock %}

ilogic/templates/vpkaak/input_nomor_ba.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
    <div class="col-12">
        <div class="card-body">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h5>Aksi Verifikator</h5>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="hidden" name="action" value="update_status">
                        <button class="btn btn-primary w-100" type="submit">Simpan</button>
                    </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

ilogic/templates/vpkaak/monitoring_data_sampling_vpkaak.html
{% extends 'base.html' %}

{% block content %}
<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card table-card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>Monitoring Data Sampling VPK AAK</h5>
        </div>
    <div id="output" style="margin: 30px;"></div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.js" integrity="sha512-XgJh9jgd6gAHu9PcRBBAp0Hda8Tg87zi09Q2639t0tQpFFQhGpeCgaiEFji36Ozijjx9agZxB0w53edOFGCQ0g==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.23.0/pivot.min.css" integrity="sha512-BDStKWno6Ga+5cOFT9BUnl9erQFzfj+Qmr5MDnuGqTQ/QYDO1LPdonnF6V6lBO6JI13wg29/XmPsufxmCJ8TvQ==" crossorigin="anonymous" />

<script>
    // scroller active
    $('#dashboard_cbg').addClass('active');
    $('#vk').addClass('active');
    // pivot table js
    $(function(){
    $.getJSON("{% url 'vpkaak:api_json_data_sampling_vpkaak' %}", function(mps) {
        $("#output").pivotUI(mps,
            { rows: ["Nmkclayan", "register__nomor_register"], cols: ["status"] },
            false
        );
    });
 });
</script>
{% endblock %}

ilogic/templates/vpkaak/preview_sampling_data_import_cbg.html
{% extends 'base.html' %}

{% block content %}
<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card table-card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>Preview Daftar Sampling Data Klaim</h5>
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="file_name" value="{{file_name}}">
                <input type="hidden" name="register" value="{{register}}">
                <input type="hidden" name="password" value="{{password}}">
                <input type="hidden" name="action" value="confirm">
                <button class="btn btn-primary" {% if total_data_invalid > 0 %}disabled{% endif %}>CONFIRM</button>
            </form>
        </div>
        <div class="card-body">
            <center><button class="btn btn-primary w-75 mb-2 mt-2" disabled>(DATA VALID: {{total_data_valid}})</button></center>
            <div class="table-responsive mb-5" style="height:400px; overflow-y:scroll;">
                <table class="table table-hover table-borderless mb-0">
                    <thead>
                    <tr>
                        {% for column in preview_data_valid.columns %}
                        <th scope="col">{{column}}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for index,row in preview_data_valid.iterrows %}
                    <tr>
                        {% for value in row %}
                        <td>{{value}}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}