ilogic/faskes/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('register', views.register, name='register'),
    path('daftar-register', views.daftar_register, name='daftar-register'),
    path('detail-register/<int:pk>', views.detail_register, name='detail-register'),

    # cbg
    path('daftar/dataklaim/cbg/pending/dispute/', views.daftar_data_klaim_pending_dispute_cbg, name='daftar_data_klaim_pending_dispute_cbg'),
    path('detail/dataklaim/cbg/pending/dispute/<int:pk>/', views.detail_data_klaim_pending_dispute_cbg, name='detail_data_klaim_pending_dispute_cbg'),

    # obat
    path('daftar/dataklaim/obat/pending/dispute/', views.daftar_data_klaim_pending_dispute_obat, name='daftar_data_klaim_pending_dispute_obat'),
    path('detail/dataklaim/obat/pending/dispute/<int:pk>/', views.detail_data_klaim_pending_dispute_obat, name='detail_data_klaim_pending_dispute_obat'),

]

ilogic/user/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('ubahpassword', views.ubahpassword, name='ubahpassword'),
    path('logout', views.user_logout, name='logout'),

    path('new-user/', views.create_user_kantor_cabang, name='web_usr_add'),
    path('kanca/', include([
        path('user/change/group/<pk>/', views.change_group, name='kanca_grp_change'),
        path('user/group/add/kantorcabang', views.add_group, name='kanca_grp_add'),
        path('user/change/password/<pk>/', views.change_password, name='kanca_usr_passwd'),
        path('', views.user_per_kanca, name='kanca_user_list')
    ])),

    path('faskes/', include([
        path('', views.user_per_faskes, name='cbg_user_list')
    ])),

    path('new-user/faskes/', views.create_user_faskes, name='create_user_faskes'),

    path('list/verifikator/', views.user_per_verifikator, name='user_per_verifikator'),
    path('edit/active/verifikator/<int:pk>/', views.edit_user_verifikator_active, name='edit_user_verifikator_active'),
    path('edit/staff/verifikator/<int:pk>/', views.edit_user_verifikator_staff, name='edit_user_verifikator_staff'),
]

ilogic/viis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from user import views
from user.views import dashboard

admin.site.site_header = "BPJS Kesehatan"
admin.site.site_title = "BPJS Kesehatan"
admin.site.index_title = "Selamat Datang di Portal BPJS Kesehatan"

admin.site.login = views.user_login

urlpatterns = [
    path('admin/ilogic/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('faskes/', include(('faskes.urls', 'faskes'), namespace='faskes')),
    path('klaim/', include(('klaim.urls', 'klaim'), namespace='klaim')),
    path('verifikator/', include(('verifikator.urls', 'verifikator'), namespace='verifikator')),
    path('staff/', include(('staff.urls', 'staff'), namespace='staff')),
    path('captcha/', include('captcha.urls')),
    path('monitoring/', include(('monitoring.urls', 'monitoring'), namespace='monitoring')),
    path('supervisor/', include(('supervisor.urls', 'supervisor'), namespace='supervisor')),
    # path('dokumentasi/', include(('dokumentasi.urls', 'dokumentasi'), namespace='dokumentasi')),
    path('supervisorkp/', include(('supervisorkp.urls', 'supervisorkp'), namespace='supervisorkp')),
    path('vpkaak/', include(('vpkaak.urls', 'vpkaak'), namespace='vpkaak')),
    path('metafisik/', include(('metafisik.urls', 'metafisik'), namespace='metafisik')),


    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ilogic/faskes/models.py
from django.db import models

from user.models import User
from .choices import (
    JenisFaskesChoices
)


class Kepwil(models.Model): #kepwil
    nama = models.CharField(max_length=100, unique=True)
    kode_kepil = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f'{self.nama}'


class KantorCabang(models.Model):
    nama = models.CharField(max_length=100, unique=True)
    kode_cabang = models.CharField(max_length=30, unique=True)
    kepwil = models.ForeignKey(Kepwil, on_delete=models.CASCADE) #kepwil
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f'{self.nama}'


class Faskes(models.Model):
    nama = models.CharField(max_length=250)
    kode_ppk = models.CharField(max_length=100, unique=True)
    jenis = models.CharField(max_length=50,
                             choices=JenisFaskesChoices.choices, blank=True, null=True)

    kantor_cabang = models.ForeignKey(KantorCabang, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f'{self.nama}'

ilogic/faskes/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import SelectDateWidget
from django.utils.translation import gettext_lazy as _

from klaim.models import (
    RegisterKlaim, DataKlaimCBG, JawabanPendingDispute, JenisKlaim, DataKlaimObat
)

import datetime

tahun_hari_ini = datetime.datetime.today().year

YEARS = [x for x in range(2016, tahun_hari_ini + 1)]
YEARS.reverse()

STATUS_CHOICES_DATA_KLAIM_FASKES = (
    ('Pembahasan', 'Pembahasan'),
    ('Tidak Layak', 'Tidak Layak'),
)


class RegisterKlaimForm(forms.ModelForm):
    jenis_klaim = forms.ModelChoiceField(queryset=JenisKlaim.objects.all(), empty_label="Pilih Jenis Klaim")
    kasus_rawat_jalan_aju = forms.IntegerField(widget=forms.NumberInput(attrs={'min': 0, 'oninput':
        "this.value =!!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null", }))
    biaya_rawat_jalan_aju = forms.IntegerField(widget=forms.NumberInput(attrs={'min': 0, 'oninput':
        "this.value =!!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null"}))
    kasus_rawat_inap_aju = forms.IntegerField(widget=forms.NumberInput(attrs={'min': 0, 'oninput':
        "this.value =!!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null"}))
    biaya_rawat_inap_aju = forms.IntegerField(widget=forms.NumberInput(attrs={'min': 0, 'oninput':
        "this.value =!!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null"}))
    bulan_pelayanan = forms.DateField(widget=SelectDateWidget(years=YEARS))
    nomor_surat_pengajuan_rs = forms.CharField(min_length=5)

    class Meta:
        model = RegisterKlaim
        fields = [
            'jenis_klaim',
            'kasus_rawat_jalan_aju',
            'biaya_rawat_jalan_aju',
            'kasus_rawat_inap_aju',
            'biaya_rawat_inap_aju',
            'bulan_pelayanan',
            'nomor_surat_pengajuan_rs',
            # "is_pengajuan_ulang"
        ]
        # widgets = {
        #     'bulan_pelayanan': SelectDateWidget(years=YEARS)
        # }
        # # labels = {
        # #     "is_pengajuan_ulang": _("Pengajuan ulang pending/dispute")
        # # }
        # # help_texts = {
        # #     "is_pengajuan_ulang": _("Ceklis jika ini pengajuan ulang data klaim pending/dispute.")
        # # }


class UpdateRegisterKlaimForm(forms.ModelForm):
    class Meta:
        model = RegisterKlaim
        fields = [
            'jenis_klaim',
            'kasus_rawat_jalan_aju',
            'biaya_rawat_jalan_aju',
            'kasus_rawat_inap_aju',
            'biaya_rawat_inap_aju',
            'bulan_pelayanan',
            'nomor_surat_pengajuan_rs'
        ]
        widgets = {
            'bulan_pelayanan': SelectDateWidget(years=YEARS)
        }


class UpdateRegisterKlaimDisableForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["jenis_klaim"].disabled = True
        self.fields["kasus_rawat_jalan_aju"].disabled = True
        self.fields["biaya_rawat_jalan_aju"].disabled = True
        self.fields["kasus_rawat_inap_aju"].disabled = True
        self.fields["biaya_rawat_inap_aju"].disabled = True
        self.fields["bulan_pelayanan"].disabled = True
        self.fields["nomor_surat_pengajuan_rs"].disabled = True

    class Meta:
        model = RegisterKlaim
        fields = [
            'jenis_klaim',
            'kasus_rawat_jalan_aju',
            'biaya_rawat_jalan_aju',
            'kasus_rawat_inap_aju',
            'biaya_rawat_inap_aju',
            'bulan_pelayanan',
            'nomor_surat_pengajuan_rs'
        ]
        widgets = {
            'bulan_pelayanan': SelectDateWidget(years=YEARS)
        }


class DataKlaimCBGFaskesForm(forms.ModelForm):
    status = forms.ChoiceField(choices=STATUS_CHOICES_DATA_KLAIM_FASKES)

    class Meta:
        model = DataKlaimCBG
        fields = [
            'status',
        ]


class DataKlaimObatFaskesForm(forms.ModelForm):
    status = forms.ChoiceField(choices=STATUS_CHOICES_DATA_KLAIM_FASKES)

    class Meta:
        model = DataKlaimObat
        fields = [
            'status',
        ]


class JawabanPendingDisputeForm(forms.ModelForm):
    class Meta:
        model = JawabanPendingDispute
        fields = [
            'ket_jawaban_pending',
        ]

ilogic/templates/faskes/daftar_data_klaim_pending_dispute_cbg.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load my_tags %}

{% block content %}

<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>
                Data Klaim Pending/Dispute CBG <span class="badge bg-danger">{{ request.count_data_klaim }}</span>
            </h5>
            <form>
                    <button type="submit" class="btn btn-primary" name="export" value="export"><i class="fas fa-file-download"><span style="font-size: 15px"> Download</span></i></button>
            </form>
        </div>

        <div class="card-body">
              <form class="row row-cols-md-auto g-3 align-items-center">
{#                <div class="col-12">#}
{#                  <label class="sr-only" for="id_status">JNSPEL</label>#}
{#                  <select class="form-select" name="JNSPEL" id="id_JNSPEL">#}
{#                      <option selected value="">JNSPEL...</option>#}
{#                      <option value="Rawat Inap" {% if request.GET.JNSPEL == 'Rawat Inap' %}selected {% endif %}>Rawat Inap</option>#}
{#                      <option value="Rawat Jalan" {% if request.GET.JNSPEL == 'Rawat Jalan' %}selected {% endif %}>Rawat Jalan</option>#}
{#                  </select>#}
{#                </div>#}
{#                <div class="col-12">#}
{#                  <label class="sr-only" for="id_status">Status</label>#}
{#                  <select class="form-select" name="status" id="id_status">#}
{#                      <option selected value="">Status...</option>#}
{#                      <option value="Pending" {% if request.GET.status == 'Pending' %}selected {% endif %}>Pending</option>#}
{#                      <option value="Dispute" {% if request.GET.status == 'Dispute' %}selected {% endif %}>Dispute</option>#}
{#                      <option value="Pembahasan" {% if request.GET.status == 'Pembahasan' %}selected {% endif %}>Pembahasan</option>#}
{#                  </select>#}
{#                </div>#}
                  {{ myFilter.form | crispy }}
                <div class="col-12">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
        </div>
{#        <form>#}
{#          <div class="form-row align-items-center container-fluid">#}
{#            <div class="col-auto my-1">#}
{#              {{myFilter.form.namars }}#}
{#            </div>#}
{#            {{ myFilter.form.media }}#}
{#            <div class="col-auto my-1">#}
{#                <select class="custom-select mr-sm-2" name="Status" id="id_Status">#}
{#                  <option selected value="">Status...</option>#}
{#                  <option value="Proses" {% if request.GET.Status == 'Proses' %}selected {% endif %}>Proses</option>#}
{#                  <option value="Layak" {% if request.GET.Status == 'Layak' %}selected {% endif %}>Layak</option>#}
{#                  <option value="Pending" {% if request.GET.Status == 'Pending' %}selected {% endif %}>Pending</option>#}
{#                  <option value="Dispute" {% if request.GET.Status == 'Dispute' %}selected {% endif %}>Dispute</option>#}
{#                  <option value="Tidak Layak" {% if request.GET.Status == 'Tidak Layak' %}selected {% endif %}>Tidak Layak</option>#}
{#                </select>#}
{#            </div>#}
{##}
{#            <div class="col-auto my-1">#}
{#              <button type="submit" class="" name="export" value="export"><img src="https://img.icons8.com/color/32/000000/export-excel.png"/></button>#}
{#            </div>#}
{#          </div>#}
{#        </form>#}
        <div class="table-responsive">
                <table class="table table-xs table-hover table-borderless mb-0" id="data-table">
                    <thead>
                        <tr>
                            <th scope="col">Status</th>
                            <th scope="col">RS</th>
                            <th scope="col">No REG</th>
                            <th scope="col">No SEP</th>
                            <th scope="col">In</th>
                            <th scope="col">Out</th>
                            <th scope="col">Jns Pel</th>
                            <th scope="col">No Kartu</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Poli</th>
                            <th scope="col">CBG</th>
                            <th scope="col">Biaya</th>
{#                            <th scope="col">Ket. Pending</th>#}
{#                            <th scope="col">Jawaban</th>#}
                        </tr>
                    </thead>
                    <tbody>
                    {% for data_klaim in data_klaim %}
                    <tr>
                        <td>
                            {% if data_klaim.status == 'Pending' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_cbg' data_klaim.id %}?next={{ request.get_full_path|urlencode }}">
                                    <button type="button" class="btn btn-warning btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Dispute' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_cbg' data_klaim.id %}?next={{ request.get_full_path|urlencode }}">
                                    <button type="button" class="btn btn-dark btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Pembahasan' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_cbg' data_klaim.id %}?next={{ request.path|urlencode }}">
                                    <button type="button" class="btn btn-info btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Tidak Layak' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_cbg' data_klaim.id %}?next={{ request.path|urlencode }}">
                                    <button type="button" class="btn btn-danger btn-sm">{{ data_klaim.status }}</button>
                            {% endif %}
                        </td>
                        <td>{{data_klaim.faskes.nama}}</td>
                        <td>{{data_klaim.register_klaim.nomor_register_klaim}}</td>
                        <td>{{data_klaim.NOSEP}}</td>
                        <td>{{data_klaim.TGLSEP}}</td>
                        <td>{{data_klaim.TGLPULANG}}</td>
                        <td>{{data_klaim.JNSPEL}}</td>
                        <td>{{data_klaim.NOKARTU}}</td>
                        <td>{{data_klaim.NMPESERTA}}</td>
                        <td>{{data_klaim.bupel|date:'M-y'}}</td>
                        <td>{{data_klaim.KDINACBG}}</td>
                        <td>{{data_klaim.BYPENGAJUAN}}</td>
{#                        <td>{{data_klaim.ket_pending_dispute}}</td>#}
{#                        <td>{{data_klaim.ket_jawaban_pending}}</td>#}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<!-- Pagination -->
<div class="pagination justify-content-center">
    <span class="step-links">
        {% if data_klaim.has_previous %}
            <a href="?{% param_replace page=1 %}">&laquo; First</a>
            {% if data_klaim.previous_page_number != 1 %}
            <a href="?{% param_replace page=data_klaim.previous_page_number %}">Previous</a>
            {% endif %}
        {% endif %}

        Page {{ data_klaim.number }} of {{ data_klaim.paginator.num_pages }}

        {% if data_klaim.has_next %}
            {% if data_klaim.next_page_number != paginator.num_pages %}
            <a href="?{% param_replace page=data_klaim.next_page_number %}">Next</a>
            {% endif %}
            <a href="?{% param_replace page=data_klaim.paginator.num_pages %}">Last &raquo;</a>
        {% endif %}
        <p>Data Klaim {{ data_klaim.start_index }} - {{ data_klaim.end_index }} </p>
    </span>
</div>

{#<script>#}
{#    var search = ''#}
{#    var status = ''#}
{#    var grid = new gridjs.Grid({#}
{#        columns: ["DETAIL", "NOSEP", "NOKARTU", "NMPESERTA", "BUPEL", "STATUS", "FASKES"],#}
{#        pagination: {#}
{#            limit: 10,#}
{#            server: {#}
{#                url: (prev, page, limit) => `${prev}?limit=${limit}&offset=${page * limit}&search=${search}&status=${status}`#}
{#            }#}
{#        },#}
{#        server: {#}
{#            url: '/verifikator/api/data-klaim',#}
{#            then: data => data.results.map(data =>#}
{#                [ gridjs.html(`<a href="/verifikator/detail-data-klaim/${data.id}" class="btn btn-primary">DETAIL</a>`), data.NOSEP, data.NOKARTU, data.NMPESERTA, data.bupel, data.status, data.faskes]#}
{#                ),#}
{#            total: data => data.count#}
{#            }#}
{#   })#}
{#   grid.render(document.getElementById("data-klaim"))#}
{##}
{#   document.getElementById("input-search").addEventListener("input", function(e){#}
{#    search = e.target.value#}
{#    grid.updateConfig({#}
{#    }).forceRender()#}
{#   })#}
{##}
{#   document.getElementById("input-status").addEventListener("input", function(e){#}
{#    status = e.target.value#}
{#    grid.updateConfig({#}
{#    }).forceRender()#}
{#   })#}
{##}
{##}
{##}
{#</script>#}
{% endblock %}

ilogic/templates/faskes/daftar_data_klaim_pending_dispute_obat.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load my_tags %}
{% load humanize %}

{% block content %}

<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>
                Data Klaim Pending/Dispute Obat <span class="badge bg-danger">{{ request.count_data_klaim_obat }}</span>
            </h5>
            <form>
                    <button type="submit" class="btn btn-primary" name="export" value="export"><i class="fas fa-file-download"><span style="font-size: 15px"> Download</span></i></button>
            </form>
        </div>

        <div class="card-body">
              <form class="row row-cols-md-auto g-3 align-items-center">
                  {{ myFilter.form | crispy }}
                <div class="col-12">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
        </div>
        <div class="table-responsive">
                <table class="table table-xs table-hover table-borderless mb-0" id="data-table">
                    <thead>
                        <tr>
                            <th scope="col">Status</th>
                            <th scope="col">RS</th>
                            <th scope="col">NO REG</th>
                            <th scope="col">Rufil</th>
                            <th scope="col">NO SEP Apotek</th>
                            <th scope="col">NO SEP Asal</th>
                            <th scope="col">NO Resep</th>
                            <th scope="col">Tgl Resep</th>
                            <th scope="col">KdJenis</th>
                            <th scope="col">NO Kartu</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Biaya</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for data_klaim in data_klaim %}
                    <tr>
                        <td>
                            {% if data_klaim.status == 'Pending' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_obat' data_klaim.id %}?next={{ request.get_full_path|urlencode }}">
                                    <button type="button" class="btn btn-warning btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Dispute' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_obat' data_klaim.id %}?next={{ request.get_full_path|urlencode }}">
                                    <button type="button" class="btn btn-dark btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Pembahasan' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_obat' data_klaim.id %}?next={{ request.path|urlencode }}">
                                    <button type="button" class="btn btn-info btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% elif data_klaim.status == 'Tidak Layak' %}
                                <a href="{% url 'faskes:detail_data_klaim_pending_dispute_obat' data_klaim.id %}?next={{ request.path|urlencode }}">
                                    <button type="button" class="btn btn-danger btn-sm">{{ data_klaim.status }}</button>
                                </a>
                            {% endif %}
                        </td>
                        <td>{{ data_klaim.faskes.nama }}</td>
                        <td>{{ data_klaim.register_klaim.nomor_register_klaim }}</td>
                        <td>{{ data_klaim.rufil }}</td>
                        <td>{{ data_klaim.NoSEPApotek }}</td>
                        <td>{{ data_klaim.NoSEPAsalResep }}</td>
                        <td>{{ data_klaim.NoResep }}</td>
                        <td>{{ data_klaim.TglResep | date:'d-m-Y' }}</td>
                        <td>{{ data_klaim.KdJenis }}</td>
                        <td>{{ data_klaim.NoKartu }}</td>
                        <td>{{ data_klaim.NamaPeserta }}</td>
                        <td style="text-align: right">{{ data_klaim.ByTagApt|intcomma }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<!-- Pagination -->
<div class="pagination justify-content-center">
    <span class="step-links">
        {% if data_klaim.has_previous %}
            <a href="?{% param_replace page=1 %}">&laquo; First</a>
            {% if data_klaim.previous_page_number != 1 %}
            <a href="?{% param_replace page=data_klaim.previous_page_number %}">Previous</a>
            {% endif %}
        {% endif %}

        Page {{ data_klaim.number }} of {{ data_klaim.paginator.num_pages }}

        {% if data_klaim.has_next %}
            {% if data_klaim.next_page_number != paginator.num_pages %}
            <a href="?{% param_replace page=data_klaim.next_page_number %}">Next</a>
            {% endif %}
            <a href="?{% param_replace page=data_klaim.paginator.num_pages %}">Last &raquo;</a>
        {% endif %}
        <p>Data Klaim {{ data_klaim.start_index }} - {{ data_klaim.end_index }} </p>
    </span>
</div>

{% endblock %}

ilogic/templates/faskes/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card table-card">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5>Monitoring Register Klaim - Data Klaim</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-borderless mb-0">
                    <thead>
                    <tr>
                        {% for column in preview_data.columns %}
                        <th scope="col">{{ column }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for index,row in preview_data.iterrows %}
                    <tr>
                        {% for value in row %}
                        <td>{% if value == ' nan ' %} {% else %} {{value}} {% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

ilogic/templates/faskes/detail_register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card">
        <div class="card-header">
            <h5>Detail Register</h5>
        </div>
        <div class="card-body">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3" role="alert">
                        {{ message }}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}

            {% if register.status == 'Dikembalikan' %}
            <!-- test  -->
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <div class="form-group">
                    <button class="btn btn-primary text-light w-100" type="submit">Update</button>
                </div>
            </form>
            {% else %}
            <form>
                {{form_disable|crispy}}
            </form>
            {% endif %}
            <!-- endtest  -->

        </div>
    </div>
</div>
<div class="row"></div>
<div class="row"></div>

<script>
    document.getElementById("id_bulan_pelayanan_day").style.display="none";
</script>
{% endblock %}

ilogic/templates/faskes/input.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<div class="col-xl-12 col-md-12 mb-4 mt-4">
    <div class="card">
        <div class="card-header">
            <h5>Input Data RS</h5>
        </div>
        <div class="card-body">
                {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3" role="alert">
                                {{ message }}
                              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                {% endif %}

            <!-- test  -->
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <div class="form-group">
                    <button class="btn btn-primary text-light w-100" type="submit">Submit</button>
                </div>
            </form>
            <!-- endtest  -->

        </div>
    </div>
</div>
<div class="row"></div>
<div class="row"></div>

<script>
    document.getElementById("id_bulan_pelayanan_day").style.display="none";
</script>
{% endblock %}